# Generated by Django 3.1.1 on 2020-10-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_auto_20201001_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='onsale',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='onsale',
            name='sale_start',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='onsale',
            name='sale_expiry',
            field=models.DateTimeField(default=None),
        ),
    ]
