# Generated by Django 3.1.1 on 2020-10-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_auto_20201001_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='featured',
            name='feature_start',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='featured',
            name='feature_expiry',
            field=models.DateTimeField(default=None),
        ),
    ]
