# Generated by Django 3.1.1 on 2020-10-01 10:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id_member', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=128)),
                ('name', models.CharField(max_length=40)),
                ('sex', models.CharField(max_length=1)),
                ('birth_date', models.DateField()),
                ('register_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id_trx', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_member', models.IntegerField()),
                ('id_item', models.IntegerField()),
                ('trx_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-trx_date'],
            },
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id_wishlist', models.AutoField(primary_key=True, serialize=False)),
                ('id_member', models.IntegerField()),
                ('id_item', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
