# Generated by Django 3.1.1 on 2020-10-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=128, unique=True),
        ),
        migrations.AlterModelTable(
            name='member',
            table='bajigur_member',
        ),
        migrations.AlterModelTable(
            name='transaction',
            table='bajigur_transaction',
        ),
        migrations.AlterModelTable(
            name='wishlist',
            table='bajigur_wishlist',
        ),
    ]
