# Generated by Django 3.1.1 on 2020-10-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20201001_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='qty',
            field=models.IntegerField(default=1),
        ),
    ]
