# Generated by Django 3.1.1 on 2020-10-02 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_transaction_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
